export const ActionTypes = {
  // LOGIN_REQUEST: 'LOGIN_REQUEST',
  // LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  // LOGIN_FAILURE: 'LOGIN_FAILURE',
  // SET_MESSAGE: 'SET_MESSAGE',
  FETCH_ITEMS: 'FECTH_ITEMS',
  SET_ITEMS: 'SET_ITEMS',
  SELECTED_ITEM: 'SELECTED_ITEM',
  SET_BUTTON: 'SET_BUTTON',
};
